### ISSUE TITLE
nh_group: tibble rownames

### ISSUE THREAD

**Issue by tghoward** [VANatHeritage/nhSDM#1]
when using a sf, I get this warning, fyi: `Setting row names on a tibble is deprecated.`
Output seems to be fine. 

Here's a paste of the call and all the output:

> ptout2 <- nh_group(pts.aea, sep.dist = d, union = FALSE )
Distances calculated in coordinate system units...
Warning message:
Setting row names on a tibble is deprecated. 

Cheers, 
Tim

**Comment by dnbucklin** [comment]
Thanks. I guess you must be using `read_sf` to load your data, which loads into a `tibble`, rather than `st_read` which uses `data.frame`s, as I was testing on. 

This doesn't affect the result as you noted, but I will update to avoid setting row names at all.

**Comment by dnbucklin** [comment]
Fixed 03d578e, but may revisit to allow output of `tibble` when input is `tibble`. `data.frame` is always ouput now.
